
package com.soap.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StatisticService", targetNamespace = "http://service.module.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StatisticService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "statistictwo", targetNamespace = "http://service.module.com/", className = "com.soap.client.Statistictwo")
    @ResponseWrapper(localName = "statistictwoResponse", targetNamespace = "http://service.module.com/", className = "com.soap.client.StatistictwoResponse")
    public List<Integer> statistictwo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "statisticone", targetNamespace = "http://service.module.com/", className = "com.soap.client.Statisticone")
    @ResponseWrapper(localName = "statisticoneResponse", targetNamespace = "http://service.module.com/", className = "com.soap.client.StatisticoneResponse")
    public List<Integer> statisticone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
