
package com.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StatisticService", targetNamespace = "http://serviceImpl.service.module.com/", wsdlLocation = "http://localhost:8081/StatisticService?wsdl")
public class StatisticService_Service
    extends Service
{

    private final static URL STATISTICSERVICE_WSDL_LOCATION;
    private final static WebServiceException STATISTICSERVICE_EXCEPTION;
    private final static QName STATISTICSERVICE_QNAME = new QName("http://serviceImpl.service.module.com/", "StatisticService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/StatisticService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATISTICSERVICE_WSDL_LOCATION = url;
        STATISTICSERVICE_EXCEPTION = e;
    }

    public StatisticService_Service() {
        super(__getWsdlLocation(), STATISTICSERVICE_QNAME);
    }

    public StatisticService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATISTICSERVICE_QNAME, features);
    }

    public StatisticService_Service(URL wsdlLocation) {
        super(wsdlLocation, STATISTICSERVICE_QNAME);
    }

    public StatisticService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATISTICSERVICE_QNAME, features);
    }

    public StatisticService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StatisticService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StatisticService
     */
    @WebEndpoint(name = "StatisticServiceImplPort")
    public StatisticService getStatisticServiceImplPort() {
        return super.getPort(new QName("http://serviceImpl.service.module.com/", "StatisticServiceImplPort"), StatisticService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StatisticService
     */
    @WebEndpoint(name = "StatisticServiceImplPort")
    public StatisticService getStatisticServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceImpl.service.module.com/", "StatisticServiceImplPort"), StatisticService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATISTICSERVICE_EXCEPTION!= null) {
            throw STATISTICSERVICE_EXCEPTION;
        }
        return STATISTICSERVICE_WSDL_LOCATION;
    }

}
